Repository bitwarden/desktop, pull requests merged in 2022-02, with the labels that each got.

#1281 [bug] Add options string
  src/locales/en/messages.json
Labels: bug

#1291 [Icons] FF - requested icon changes
  package-lock.json
  package.json
  src/app/vault/add-edit.component.html
  src/app/vault/groupings.component.html
  webpack.renderer.js
Labels: enhancement

#1355 Added linter workflow
  .github/workflows/workflow-linter.yml
Labels: DevOps

#1370 [Icons] Added missing custom field sort icon
  src/app/vault/add-edit-custom-fields.component.html
Labels: bug

#1376 Added dry run logic
  .github/workflows/release.yml
Labels: DevOps
